### ISSUE TITLE
PowerShell 2.0 incompatible module

### ISSUE THREAD

**Issue by mubix** [nullbind/Powershellery#1]
Get-SPN uses "ordered" which is a [PowerShell 3.0+ only feature](http://stackoverflow.com/questions/7802406/use-cases-of-ordered-the-new-powershell-3-0-feature). This means that the module errors out and does not return anything when run on PowerShell 2.0 only hosts:

Link: https://github.com/nullbind/Powershellery/blob/master/Stable-ish/Get-SPN/Get-SPN.psm1#L195

**Comment by nullbind** [comment]
Bummer - I'll take a look when I get a little time to play with it.  Thanks for letting me know.

**Comment by nullbind** [comment]
I think this is covered by PowerUpSQL now. :) Sorry the the delayed response. :)
